export default {
    LOGIN_ATTEMPT: "LOGIN_ATTEMPT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    GET_REPOSITORY_ATTEMPT: "GET_REPOSITORY_ATTEMPT",
    GET_REPOSITORY_SUCCESS: "GET_REPOSITORY_SUCCESS",
    GET_REPOSITORY_FAILURE: "GET_REPOSITORY_FAILURE",
    GET_ISSUES_ATTEMPT: "GET_ISSUES_ATTEMPT",
    GET_ISSUES_SUCCESS: "GET_ISSUES_SUCCESS",
    GET_ISSUES_FAILURE: "GET_ISSUES_FAILURE",
    SET_SELECTED_REPOSITORY: "SET_SELECTED_REPOSITORY",
    SET_ISSUE_ORDER: "SET_ISSUE_ORDER",
};